twig:
    file_name_pattern: '*.twig'
    globals:
      search: ''
      location: ''
      category: ''
      minPrice: null
      maxPrice: null

when@test:
    twig:
        strict_variables: true
